CREATE TABLE IF NOT EXISTS SELLER(
  ID INT,
  NAME VARCHAR(255),
  ADRESS VARCHAR(255),
  ZIP_CODE INT(5),
  CITY VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
  ID INT,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  IMAGE_URL VARCHAR(255),
  PRICE INT,
  CREATED_ON DATE,
  SELLER_ID INT
);